### ISSUE TITLE
pdf 

### ISSUE THREAD

**Issue by iAmKarin** [PacktPublishing/The-Modern-JavaScript-Bootcamp-2019#1]
Hello,
where can i find the pdf of this course? 
have a nice day!
Karin

**Comment by ewbrower** [comment]
The PDF is in the "1. Course Overview" directory: https://github.com/PacktPublishing/The-Modern-JavaScript-Bootcamp-2019/blob/master/1.%20Course%20Overview/PDF%20Guide.pdf

**Comment by iAmKarin** [comment]
Thanks!
